name: kolkatametro
description: "Kolkata Metro App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  provider: ^6.1.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.6.1
  sliding_up_panel: ^2.0.0+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/metro.jpg
    - lib/assets/map.svg
    - lib/assets/google_logo.svg
    - lib/assets/google_logo.png
    - lib/assets/kolkata_metro_data.json
    - lib/assets/ios_background.jpg


