name: kolkatametro
description: "Kolkata Metro App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any
  provider: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  google_sign_in: ^6.2.1
  google_maps_flutter: any
  sliding_up_panel: any
  google_fonts: any
  shared_preferences: any
  geolocator: any
  geocoding: any
  intl: any
  local_auth: any
  mailer: any
  crypto: any
  http: any
  flutter_secure_storage: any
  pin_code_fields: any
  timer_builder: any
  liquid_glass_renderer: any
  flutter_animated_button: any
  rive: any
  sms_autofill: any 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - lib/assets/metro.jpg
    - lib/assets/map.svg
    - lib/assets/google_logo.svg
    - lib/assets/kolkata_metro_data.json
    - lib/assets/trip.png
    - lib/assets/shuttle.png
    - lib/assets/rental.png
    - lib/assets/intercity.png
    - lib/assets/promo.png
    - lib/assets/weekend.png
    - lib/assets/welcomecircle.jpeg
    - lib/assets/logo.svg
    - lib/assets/loading.gif
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/