// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KznVGFOYXCsdLEjH8dtyygqYOySFqwM',
    appId: '1:102121405807:web:bef447ba15fad2e0ed7c9a',
    messagingSenderId: '102121405807',
    projectId: 'kolkatametroflutter',
    authDomain: 'kolkatametroflutter.firebaseapp.com',
    storageBucket: 'kolkatametroflutter.firebasestorage.app',
    measurementId: 'G-S7J68J7M8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKvFxvuf4GxmElTZhDra3l0ycVkr-I5p8',
    appId: '1:102121405807:android:fca9619d1c88d9d3ed7c9a',
    messagingSenderId: '102121405807',
    projectId: 'kolkatametroflutter',
    storageBucket: 'kolkatametroflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7L-nDk13EQh-WYv969ZaJuN8WdlGFOs',
    appId: '1:102121405807:ios:47dfaac85ded24eeed7c9a',
    messagingSenderId: '102121405807',
    projectId: 'kolkatametroflutter',
    storageBucket: 'kolkatametroflutter.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL7L-nDk13EQh-WYv969ZaJuN8WdlGFOs',
    appId: '1:102121405807:ios:47dfaac85ded24eeed7c9a',
    messagingSenderId: '102121405807',
    projectId: 'kolkatametroflutter',
    storageBucket: 'kolkatametroflutter.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2KznVGFOYXCsdLEjH8dtyygqYOySFqwM',
    appId: '1:102121405807:web:4c0f0c3d6f91c98eed7c9a',
    messagingSenderId: '102121405807',
    projectId: 'kolkatametroflutter',
    authDomain: 'kolkatametroflutter.firebaseapp.com',
    storageBucket: 'kolkatametroflutter.firebasestorage.app',
    measurementId: 'G-BW2CC9P4V5',
  );
}
